#!/bin/sh

if pactl info >& /dev/null; then
    for sink in `pactl list short sinks | grep 'RUNNING$' | cut -f1`; do
        pactl set-sink-volume "$sink" "+5.0%"
    done
else
    amixer -q set Master 5%+ 
fi

